### ISSUE TITLE
Won't startup (Skynode)

### ISSUE THREAD

**Issue by JustAssassinExists** [Moneylover3246/Crossplay#45]
```
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
Skynode: Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./TShock.Server -ip 0.0.0.0 -port ${SERVER_PORT} -maxplayers ${MAX_PLAYERS} -world ${WORLD_NAME}.wld -autocreate ${WORLD_SIZE}
Created new 8401x2401 DefaultCollection`1 for source: System.Void Terraria.Main::.cctor()
Error Logging Enabled.
[OTAPI] Starting up (OTAPI PC Server,3.1.19,9ab9fd1,ModFw:1.1.7).
TerrariaAPI Version: 2.1.0.0 (Protocol v1.4.4.8.1 (278), OTAPI 1.4.4.8)
[Server API] Error Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "Crossplay" has thrown an exception during initialization.
 ---> System.NotSupportedException: The provided version of this plugin is outdated and will not function properly. Check for any updates here: https://github.com/Moneylover3246/Crossplay
   at Crossplay.CrossplayPlugin.Initialize()
   at TerrariaApi.Server.PluginContainer.Initialize() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/PluginContainer.cs:line 36
   at TerrariaApi.Server.ServerApi.LoadPlugins() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 430
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 435
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game) in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 118
   at TerrariaApi.Server.HookManager.InitialiseAPI() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/HookManager.cs:line 29

```

**Comment by SirMonkeyBoy** [comment]
please close this and make it in https://github.com/SirMonkeyBoy/Crossplay/issues Moneylover hasn't updated to 1.4.4.8.1 only mine has

**Comment by SirMonkeyBoy** [comment]
It won't start as Moneylover hasn't updated Crossplay yet

**Comment by SirMonkeyBoy** [comment]
theirs a crossplay.dll in my releases on my fork #44  but update to this plugin when Moneylover updates it
