### ISSUE TITLE
Outdated, but not outdated?

### ISSUE THREAD

**Issue by DeLittleCat** [Moneylover3246/Crossplay#59]
I have the most recent version of Crossplay in the correct file, but it says I don't have it (maybe a TShock problem).
The console if it helps:
Created new 8401x2401 DefaultCollection`1 for source: System.Void Terraria.Main::.cctor()

Error Logging Enabled.

[OTAPI] Starting up (OTAPI PC Server,3.1.19,9ab9fd1,ModFw:1.1.7).

[Server API] Error Startup aborted due to an exception in the Server API initialization:

System.InvalidOperationException: Plugin "Crossplay" has thrown an exception during initialization.

---> System.NotSupportedException: The provided version of this plugin is outdated and will not function properly. Check for any updates here: https://github.com/Moneylover3246/Crossplay

at Crossplay.CrossplayPlugin.Initialize()

at TerrariaApi.Server.PluginContainer.Initialize() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/PluginContainer.cs:line 36

at TerrariaApi.Server.ServerApi.LoadPlugins() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 430
errariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/HookManager.cs:line 29

**Comment by Moneylover3246** [comment]
What release of tshock do you have?

**Comment by DeLittleCat** [comment]
5.1.3 and I have never used TShock before

**Comment by Moneylover3246** [comment]
Either the plugin or TShock haven't been properly updated to 1.4.4.9. Try to install a fresh copy of both here:
https://github.com/Moneylover3246/Crossplay/releases/tag/2.2
https://github.com/Pryaxis/TShock/releases/tag/v5.1.3

**Comment by DeLittleCat** [comment]
A new problem arose after that:
Unhandled exception

System.UnhandledExceptionEventArgs

Unhandled exception. System.TypeInitializationException: The type initializer for 'TerrariaApi.Server.ServerApi' threw an exception.

---> System.IO.FileLoadException: Could not load file or assembly 'OTAPI, Version=1.4.4.8, Culture=neutral, PublicKeyToken=null'. Could not find or load a specific file. (0x80131621)

File name: 'OTAPI, Version=1.4.4.8, Culture=neutral, PublicKeyToken=null'

---> System.IO.FileLoadException: Could not load file or assembly 'OTAPI, Version=1.4.4.8, Culture=neutral, PublicKeyToken=null'.

at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)

at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)

at Program.<>c__DisplayClass0_0.<<Main>$>g__Default_Resolving|0(AssemblyLoadContext arg1, AssemblyName arg2) in /home/runner/work/TShock/TShock/TShockLauncher/Program.cs:line 47

at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)

at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)

at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

--- End of inner exception stack trace ---

at TerrariaApi.Server.ServerApi.get_LogWriter() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 51

at TerrariaApi.Server.Program.Main(String[] args) in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/Program.cs:line 110

at Program.<>c__DisplayClass0_0.<<Main>$>g__Start|1() in /home/runner/work/TShock/TShock/TShockLauncher/Program.cs:line 65

at Program.<Main>$(String[] args) in /home/runner/work/TShock/TShock/TShockLauncher/Program.cs:line 35

Aborted (core dumped)

**Comment by Moneylover3246** [comment]
What platform are you using to run TShock (e.g: arm64, osx64)?

**Comment by DeLittleCat** [comment]
I think it was osx64
