### ISSUE TITLE
Plz Halp

### ISSUE THREAD

**Issue by hawksmith505** [Moneylover3246/Crossplay#9]
Hello, your plugin works like magic but yesterday this was working fine and this error suddenly appeared when I go through the door... both mobile and PC
 
 `[Server API] Warning Plugin "Crossplay" has had an unhandled exception thrown by one of its NetGetData handlers:
System.MissingMethodException: Method not found: 'Byte TShockAPI.Net.NetTile.get_Slope()'.
   at Crossplay.SendTileRectHandler.UpdateServerTileState(ITile tile, NetTile newTile)
   at Crossplay.SendTileRectHandler.UpdateMultipleServerTileStates(Int32 x, Int32 y, Int32 width, Int32 height, NetTile[,] newTiles)
   at Crossplay.SendTileRectHandler.ProcessTileObject(Int32 tileType, Int32 realX, Int32 realY, Int32 width, Int32 height, NetTile[,] newTiles, SendTileRectEventArgs args)
   at Crossplay.SendTileRectHandler.IterateTileRect(NetTile[,] tiles, Boolean[,] processed, SendTileRectEventArgs args)
   at Crossplay.Crossplay.GetData(GetDataEventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args) in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\HandlerCollection.cs:line 109
[Server API] Warning Plugin "Crossplay" has had an unhandled exception thrown by one of its NetGetData handlers:
System.MissingMethodException: Method not found: 'Byte TShockAPI.Net.NetTile.get_Slope()'.
   at Crossplay.SendTileRectHandler.UpdateServerTileState(ITile tile, NetTile newTile)
   at Crossplay.SendTileRectHandler.UpdateMultipleServerTileStates(Int32 x, Int32 y, Int32 width, Int32 height, NetTile[,] newTiles)
   at Crossplay.SendTileRectHandler.ProcessTileObject(Int32 tileType, Int32 realX, Int32 realY, Int32 width, Int32 height, NetTile[,] newTiles, SendTileRectEventArgs args)
   at Crossplay.SendTileRectHandler.IterateTileRect(NetTile[,] tiles, Boolean[,] processed, SendTileRectEventArgs args)
   at Crossplay.Crossplay.GetData(GetDataEventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args) in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\HandlerCollection.cs:line 109`

**Comment by Moneylover3246** [comment]
Hi, sorry for the late reply. Did you manage to get this issue fixed?
